SAMPLES = range(1,106)
CLUSTERS = ['nonperturb', 'perturb']

#sim_dir = '/home/lynnyi/single/6.3_sims_exp/'
sim_dir = '/home/lynnyi/single/6.1_sims_transcripts/'
#sim_dir = '/home/lynnyi/single/5.22_sims_genes/'
p_dir = sim_dir + '/sim_perturb/'
rsem_p_dir = sim_dir+'/rsem_perturb/'
np_dir = sim_dir + '/sim_nonperturb/'
rsem_np_dir = sim_dir + '/rsem_nonperturb/'
perturb_file = p_dir + '/perturb.tsv' 

#simulations code
model = 'log_normal'
sim_genes = 'FALSE'

#RSEM
RSEM_model = "/home/lynnyi/RSEM-1.3.0/exp/Trapnell_cluster1.stat/Trapnell_cluster1.model"

#kallisto pseudobatch
index = '/home/lynnyi/indices/kallisto_index/Trapnell_index.idx' 
kallisto = '/home/lynnyi/kallisto_del/kallisto/build/src/kallisto'
kallisto42 = '/home/lynnyi/kallisto_linux-v0.42.5/kallisto'

batchdir = sim_dir + '/pseudo_batch/'
batchfile = batchdir + '/batchfile.txt'

scde_dir = sim_dir + '/scde/'
scde_em = scde_dir + '/scde_error_models.csv'
scde_de = scde_dir + '/scde_de.csv'
scde_df = scde_dir + '/df_scde.csv'
scde_qq = scde_dir + '/scde_qqplot.png'
scde_roc = scde_dir + '/scde_roc_curve.png'
scde_fdr = scde_dir + '/scde_fdr_curve.png'

rule all:
	input:
		sim_dir + 'fdrs.tiff',


rule run_seurat:
	input:
		expand(sim_dir + '/rsem_quant_{cluster}/{sample}/abundance.tsv', cluster=CLUSTERS, sample=SAMPLES),
		expand(sim_dir + '/rsem_quant_{cluster}/{sample}/abundance.tsv', cluster=CLUSTERS, sample=SAMPLES),
	output:
		sim_dir + '/de/deseq2.rds',
		sim_dir + '/de/tobit.rds',
		sim_dir + '/de/mast.rds',
	shell:
		"""
		Rscript R/seurat.R {sim_dir}
		"""

#can choose to normalize or not
rule LR_tccs:
	input:
		batchdir + '/matrix.tsv'
	output:
		sim_dir + '/de/LR_tccs.rds'
	shell:
		"""
		Rscript R/tcc.R {sim_dir}
		"""

#performs all normalizations on transcripts by default
rule LR_transcripts:
	input:
		expand(sim_dir + '/rsem_quant_{cluster}/{sample}/abundance.tsv', cluster=CLUSTERS, sample=SAMPLES),	
	output:
		sim_dir + '/de/LR_tx.rds',
		sim_dir + '/de/LR_deseq.rds'
	shell:
		"""
		Rscript R/transcripts.R {sim_dir}
		"""

rule LR_gene:
	input:
		sim_dir + 'tximport.rds',
	output:
		sim_dir + '/de/gene.rds'
	shell:
		"""
		Rscript R/gene.R {sim_dir}
		"""

rule scde:
	input:
		sim_dir + 'tximport.rds',
	output:
		sim_dir + '/de/scde.rds'
	shell:
		"""
		Rscript /home/scde/scde.R {sim_dir}
		"""

rule roc:
	input:
		sim_dir + '/de/mast.rds',
		sim_dir + '/de/scde.rds',
		sim_dir + '/de/LR_tccs.rds',
		sim_dir + '/de/LR_tx.rds',
		sim_dir + '/de/LR_deseq.rds',
		sim_dir + '/de/LR_univariate.rds',
		sim_dir + '/de/LR_univariate_deseq.rds',
		
	output:
		sim_dir + 'fdrs.tiff'
	shell:
		"""
		Rscript R/roc.R {sim_dir}
		"""
